# Generated by Django 5.0.1 on 2024-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('sign', models.FileField(null=True, upload_to='static/signgif/', verbose_name='')),
            ],
        ),
    ]
